Resolve "Istio Helm Chart Deployment Gaps Causing Cert Creation Failure in aks Cluster"

diff --git a/osdu-istio/templates/cert-checker/cert-init-job.yaml b/osdu-istio/templates/cert-checker/cert-init-job.yaml
--- a/osdu-istio/templates/cert-checker/cert-init-job.yaml
+++ b/osdu-istio/templates/cert-checker/cert-init-job.yaml
@@ -39,6 +39,45 @@ spec:
         - |
           SIDECAR_PORT=15020
           K8S_ISTIONAMESPACE_NAME=istio-system
+          # Compare expire dates and cn of certificates in Key Vault and in istio-system namespaces
+          function check_cert_match() {
+            # Login to common resource (Already logged in)
+            # az login --identity
+            echo "[INFO] Getting secret id from appgw"
+            APPGW_SECRET_ID=$(az network application-gateway http-listener show -g ${SR_RG} --gateway-name ${APPGW_NAME} --name https-$(echo ${SR_RG} | sed 's/-rg/-vnet-httplstn/') --query 'sslCertificate.id' -o tsv)
+            export KV_CERT_NAME=$(az network application-gateway ssl-cert show --ids ${APPGW_SECRET_ID} --query 'name' -o tsv)
+            echo "[INFO] Appgw Secret configured: ${APPGW_SECRET_ID}"
+            echo "[INFO] KV Secret Name: ${KV_CERT_NAME}"
+
+            echo "[INFO] Compare expire dates of certificates in Key Vault and in istio-system namespaces"
+            echo "[INFO] k8s/${K8S_CERT_SECRET} == ${ENV_VAULT}/${KV_CERT_NAME} ??"
+            echo "[INFO] Keyvault secret decode: "
+            az keyvault certificate download  --vault-name  ${ENV_VAULT}  -n ${KV_CERT_NAME} --file ${KV_CERT_NAME}.pem
+            KV_CERT_EXPIREDATE=$(openssl x509 -in ${KV_CERT_NAME}.pem -enddate -noout |  cut -d '=' -f2)
+            KV_SUBJECT_NAME=$(openssl x509 -in ${KV_CERT_NAME}.pem  -subject -noout | cut -d '=' -f3 | sed 's/ //g')
+            KV_CERT_EXPIREDATE=$(date "+%Y-%m-%d" --date="${KV_CERT_EXPIREDATE}")
+            KV_SUM=$(echo $KV_SUBJECT_NAME $KV_CERT_EXPIREDATE | sha1sum | awk '{print $1}')
+
+            # Login to AKS (Not needed, using RBAC)
+
+            echo "[INFO] K8s secret decode: "
+            kubectl get secret -n ${K8S_ISTIONAMESPACE_NAME} ${K8S_CERT_SECRET} -o jsonpath='{.data.tls\.crt}' | base64 -d > cert.crt
+            SECRET_CERT_EXPIRE_DATE=$(openssl x509 -in cert.crt -enddate -noout |  cut -d '=' -f2)
+            K8S_SUBJECT_NAME=$(openssl x509 -in cert.crt  -subject -noout | cut -d '=' -f3 | sed 's/ //g')
+            SECRET_CERT_EXPIRE_DATE=$(date "+%Y-%m-%d" --date="${SECRET_CERT_EXPIRE_DATE}")
+            K8S_SUM=$(echo $K8S_SUBJECT_NAME $SECRET_CERT_EXPIRE_DATE | sha1sum | awk '{print $1}')
+
+            if [ ${K8S_SUM} = ${KV_SUM} ]; then
+              echo "$K8S_SUBJECT_NAME $SECRET_CERT_EXPIRE_DATE ==  $KV_SUBJECT_NAME $KV_CERT_EXPIREDATE"
+              echo "The cert in secret is up to date"
+              exit 0
+            else
+              echo "$K8S_SUBJECT_NAME $SECRET_CERT_EXPIRE_DATE =/=  $KV_SUBJECT_NAME $KV_CERT_EXPIREDATE"
+              echo "The cert in secret is not up to date"
+              echo "[INFO] Starting update routine"
+            fi
+            rm -f ${KV_CERT_NAME}.pem
+          }
 
           # Cleanup function
           cleanup() {
@@ -69,6 +108,8 @@ spec:
           # Install coreutils
           apk add --update coreutils
 
+          check_cert_match
+
 {{- if include "secret.istioKeyvaultCert" . }}
           # Download BYOC certificate from keyvault
           echo "[INFO] Download BYOC certificate from keyvault"
@@ -93,6 +134,10 @@ spec:
           -o yaml | kubectl apply -f -
 
           # Restart istio-ingressgateway pods (Not needed after istio 1.8)
+          sleep 5
+          check_cert_match
+          echo "Cannot update cert in secret"
+          exit 1
 
 {{ else }}
           echo "[INFO] Getting secrets from ${K8S_NAMESPACE_NAME} and upload to kv"
@@ -129,6 +174,10 @@ spec:
             --gateway-name ${APPGW_NAME} \
             --name ${HTTPS_LISTENER} \
             --ssl-cert ${KV_CERT_NAME}
+          sleep 5
+          check_cert_match
+          echo "Cannot update cert in secret"
+          exit 1
 {{- end }} 
       restartPolicy: Never
 {{- end }}
